//Ensure the following bits are set/unset in System Configuration Byte 1 to select the desired clock source: UCFG1.2 = 0, UCFG1.1 = 1, UCFG1.0 = 1

/***********************************************************************
MODULE:    Osc
VERSION:   1.06
CONTAINS:  Routines for configuring the clock source on the Philips
           P89LPC936
COPYRIGHT: Embedded Systems Academy, Inc. - www.esacademy.com
LICENSE:   May be freely used in commercial and non-commercial code
           without royalties provided this copyright notice remains
           in this file and unaltered
WARNING:   IF THIS FILE IS REGENERATED BY CODE ARCHITECT ANY CHANGES
           MADE WILL BE LOST. WHERE POSSIBLE USE ONLY CODE ARCHITECT
           TO CHANGE THE CONTENTS OF THIS FILE
GENERATED: On "Sep 30 2010" at "21:27:41" by Code Architect 2.06
***********************************************************************/

// SFR description needs to be included
#include <reg936.h>
#include "osc.h"

/***********************************************************************
DESC:    Initializes the oscillator to generate a CPU clock at
         7.3728 MHz
         Generates a clock out of CLKOUT pin
         Uses on-chip oscillator
RETURNS: Nothing
************************************************************************/
extern void osc_init
  (
  void
  )
{
  // clock divider
  DIVM = 0x00;
  // clock out on CLKOUT pin
  TRIM |= 0x40;
  // select low power clock (CPU clock slower than 8MHz)
  AUXR1 |= 0x80;
} // osc_init


