/***********************************************************************
MODULE:    CAPTURE COMPARE UNIT
VERSION:   1.02
CONTAINS:  Routines for configuring the Capture Compare Unit on the
           P89LPC936
COPYRIGHT: Embedded Systems Academy, Inc. - www.esacademy.com
LICENSE:   May be freely used in commercial and non-commercial code
           without royalties provided this copyright notice remains
           in this file and unaltered
WARNING:   IF THIS FILE IS REGENERATED BY CODE ARCHITECT ANY CHANGES
           MADE WILL BE LOST. WHERE POSSIBLE USE ONLY CODE ARCHITECT
           TO CHANGE THE CONTENTS OF THIS FILE
GENERATED: On "Nov 17 2010" at "02:35:06" by Code Architect 2.06
***********************************************************************/

#ifndef _CCUH_
#define _CCUH_

// Capture Compare Unit Channels
#define CCU_A 0
#define CCU_B 1
#define CCU_C 2
#define CCU_D 3

/***********************************************************************
DESC:    Initializes the Capture Compare Unit
         Capture channel A: no noise filter, rising edges, 0 edge delay
         Capture channel B: noise filter, falling edges, 0 edge delay
RETURNS: Nothing
CAUTION: Set EA to 1 after calling to enable interrupts
************************************************************************/
void ccu_init
  (
  void
  );
void start_CCU();
void stop_CCU();
#endif // _CCUH_
